import requests
from openai import OpenAI

print("DEBUG: Using AI summary version of fetch_notes.py")  # IMPORTANT

BASE_URL = "http://127.0.0.1:8000"
API_KEY = "supersecretkey123"

HEADERS = {
    "X-API-Key": API_KEY
}

# Initialize OpenAI client (reads OPENAI_API_KEY from env)
client = OpenAI()


def get_user_id_by_username(username: str):
    url = f"{BASE_URL}/users/by-username/{username}"
    response = requests.get(url, headers=HEADERS)

    print("User lookup status:", response.status_code)

    if response.status_code == 200:
        data = response.json()
        print("User data:", data)
        return data["id"]
    else:
        print("❌ User not found or error:", response.text)
        return None


def get_notes_for_user(user_id: int):
    url = f"{BASE_URL}/users/{user_id}/notes/"
    response = requests.get(url, headers=HEADERS)

    print("Notes lookup status:", response.status_code)

    if response.status_code == 200:
        return response.json()  # list of notes
    else:
        print("❌ Failed to fetch notes:", response.text)
        return None


def build_notes_text(notes):
    """Turn a list of note dicts into a single text blob for the LLM."""
    parts = []
    for note in notes:
        parts.append(f"Title: {note.get('title', '(no title)')}\nContent: {note['content']}")
    return "\n\n---\n\n".join(parts)


def summarize_notes_with_gpt4(notes_text: str) -> str | None:
    """
    Call GPT-4 via the Chat Completions API to summarize the notes.
    """
    print("Calling GPT-4 to summarize notes...")  # DEBUG LINE
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an assistant that summarizes a user's personal notes. "
                        "Produce a concise, clear summary and highlight any tasks, todos, "
                        "or important ideas."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        "Here are my notes. Please summarize them and list any action items:\n\n"
                        + notes_text
                    ),
                },
            ],
            temperature=0.3,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print("❌ Error calling OpenAI:", e)
        return None


def main():
    username = input("Enter username: ").strip()
    user_id = get_user_id_by_username(username)

    if user_id is None:
        return

    notes = get_notes_for_user(user_id)
    if not notes:
        print("No notes found for this user.")
        return

    # Print notes
    print("\nRetrieved Notes:")
    for note in notes:
        print("\n---------------------")
        print("Note ID:", note.get("id"))
        print("Title:", note.get("title"))
        print("Content:", note["content"])
        print("User ID:", note.get("user_id"))
    print("---------------------\n")

    # Build notes text
    notes_text = build_notes_text(notes)
    print("Built notes text, length:", len(notes_text))

    # Call GPT-4
    summary = summarize_notes_with_gpt4(notes_text)

    if summary is None:
        print("\n❌ Failed to generate summary.\n")
        return

    print("\n===== SUMMARY GENERATED BY GPT-4 =====\n")
    print(summary)
    print("\n======================================\n")


if __name__ == "__main__":
    main()
